# Generated by Django 4.1 on 2022-08-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="email",),
        migrations.RemoveField(model_name="profile", name="myInfo",),
        migrations.RemoveField(model_name="profile", name="mygit",),
        migrations.RemoveField(model_name="profile", name="user_pk",),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
