# Generated by Django 4.1 on 2022-08-26 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moim",
            name="admin_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moim_admin_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moim",
            name="join_users",
            field=models.ManyToManyField(
                blank=True, related_name="moim_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
