# Generated by Django 4.1 on 2022-08-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_moim_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moim",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="moim",
            name="slug",
            field=models.CharField(
                default=models.CharField(max_length=100, unique=True),
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
